version: '3.7'

services:
    app4you-frontend:
      container_name: frontend
      build:
          context: .
          dockerfile: Dockerfile
          target: prod
      ports:
          - 8080:80